# Generated by Django 5.2.8 on 2025-12-02 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('matriculaA', models.CharField(max_length=10)),
                ('curso', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('PN', 'Prefiro Não Informar')], default='M', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('departamento', models.CharField(max_length=255)),
                ('ativo', models.BooleanField()),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlunoRep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Ativa', 'Turma Ativa'), ('Concluída', 'Turma Concluída'), ('Cancelada', 'Turma Cancelada')], default='Ativa')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(null=True)),
                ('alunoRep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.alunorep', unique=True)),
                ('alunos', models.ManyToManyField(through='sistema.Matricula', to='sistema.aluno')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.professor')),
            ],
        ),
        migrations.AddField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.turma'),
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente'), ('Justificado', 'Presença Justificada')], default='Ausente', max_length=11)),
                ('data', models.DateField()),
                ('matricula_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='sistema.matricula')),
            ],
            options={
                'unique_together': {('matricula_id', 'data')},
            },
        ),
    ]
