# Generated by Django 5.2.8 on 2025-12-09 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alunorep',
            options={'verbose_name': 'Aluno Representante', 'verbose_name_plural': 'Alunos Representantes'},
        ),
        migrations.AlterModelOptions(
            name='matricula',
            options={'verbose_name': 'Matrícula', 'verbose_name_plural': 'Matrículas'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'Professor', 'verbose_name_plural': 'Professores'},
        ),
        migrations.AlterUniqueTogether(
            name='presenca',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('PN', 'Prefiro Não Informar')], default='M', max_length=2, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matriculaA',
            field=models.CharField(max_length=10, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='data_matricula',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='alunoRep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.alunorep', unique=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_inicio',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='alunorep',
            unique_together={('aluno',)},
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('aluno', 'turma')},
        ),
        migrations.CreateModel(
            name='PresencaTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('data', models.DateField(auto_now_add=True)),
                ('turma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='sistema.turma')),
            ],
            options={
                'verbose_name': 'Presença',
                'verbose_name_plural': 'Presenças',
                'unique_together': {('turma_id', 'data')},
            },
        ),
    ]
