# Generated by Django 5.2.8 on 2025-12-09 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_alter_alunorep_options_alter_matricula_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presenca',
            options={'verbose_name': 'Presença', 'verbose_name_plural': 'Presenças'},
        ),
        migrations.AlterModelOptions(
            name='presencaturma',
            options={'verbose_name': 'PresençaTurma', 'verbose_name_plural': 'PresençasTurma'},
        ),
        migrations.AlterUniqueTogether(
            name='presenca',
            unique_together={('matricula_id', 'data')},
        ),
    ]
