# Generated by Django 5.2.8 on 2025-12-09 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_alter_presenca_options_alter_presencaturma_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenca',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='presencaturma',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='presencaturma',
            name='turma_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencasT', to='sistema.turma'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(limit_choices_to={'ativo': True}, on_delete=django.db.models.deletion.CASCADE, to='sistema.professor'),
        ),
    ]
